#!/bin/bash
set -euo pipefail

# Agent Harness Docs Installer v0.4.0 — Miyo-aware triple-doc mirror
# (Claude Code + OpenAI Codex + OpenCode) with hourly launchd sync.
#
# What this installs:
#   ~/claude-code-docs/                                       Claude Code docs (flat)
#   ~/codex-docs/                                             Codex docs (flat)
#   ~/opencode-docs/                                          OpenCode docs (flat)
#   ~/Library/Caches/agent-harness-docs-mirror/                cache git clone (full repo)
#   ~/Library/Application Support/agent-harness-docs/sync.sh   sync script (all three targets)
#   ~/Library/LaunchAgents/com.mrkhachaturov.agent-harness-docs.plist   hourly job
#   ~/.claude/skills/claude-code-docs/SKILL.md                 Claude Code skill
#   ~/.claude/rules/claude-code-docs.md                        always-on rule
#   ~/.agents/skills/codex-docs/SKILL.md                       Codex skill (agentskills.io USER scope)
#   ~/.agents/skills/opencode-docs/SKILL.md                    OpenCode-docs skill (shared)
#   ~/.claude/skills/opencode-docs                             → symlink to above (for Claude Code)
#
# It also registers the Miyo MCP server with `claude`, `codex` CLIs, and
# merges a Miyo entry into ~/.config/opencode/opencode.{json,jsonc} —
# whenever those agents are installed and Miyo isn't yet registered.

REPO_URL="https://github.com/mrkhachaturov/agent-harness-docs.git"
BRANCH="main"

CLAUDE_DOCS_DIR="$HOME/claude-code-docs"
CODEX_DOCS_DIR="$HOME/codex-docs"
OPENCODE_DOCS_DIR="$HOME/opencode-docs"

CACHE_DIR="$HOME/Library/Caches/agent-harness-docs-mirror"
SUPPORT_DIR="$HOME/Library/Application Support/agent-harness-docs"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_LABEL="com.mrkhachaturov.agent-harness-docs"
PLIST_FILE="$LAUNCH_AGENTS_DIR/$PLIST_LABEL.plist"
SYNC_SCRIPT="$SUPPORT_DIR/sync.sh"

CLAUDE_SKILL_DIR="$HOME/.claude/skills/claude-code-docs"
CLAUDE_RULE_FILE="$HOME/.claude/rules/claude-code-docs.md"
CODEX_SKILL_DIR="$HOME/.agents/skills/codex-docs"

# opencode-docs is a shared skill: canonical SKILL.md lives in ~/.agents/skills/
# (which opencode AND codex read natively). For Claude Code, expose it via a
# symlink at ~/.claude/skills/opencode-docs → ~/.agents/skills/opencode-docs.
OPENCODE_SKILL_DIR="$HOME/.agents/skills/opencode-docs"
OPENCODE_SKILL_CLAUDE_LINK="$HOME/.claude/skills/opencode-docs"

# OpenCode global config. We pick whichever of .json / .jsonc already exists;
# default to .jsonc if neither is there (matches what `opencode` creates).
OPENCODE_CONFIG_DIR="$HOME/.config/opencode"

# Legacy paths from v0.2.x (claude-code-docs era)
LEGACY_CACHE_DIR="$HOME/Library/Caches/claude-code-docs-mirror"
LEGACY_SUPPORT_DIR="$HOME/Library/Application Support/claude-code-docs"
LEGACY_PLIST_LABEL="com.mrkhachaturovclaude-code-docs"
LEGACY_PLIST_FILE="$LAUNCH_AGENTS_DIR/$LEGACY_PLIST_LABEL.plist"

echo "Agent Harness Docs Installer v0.4.0"
echo "==================================="

# Platform check — launchd is macOS-only
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ This installer targets macOS (uses launchd). Detected: $OSTYPE"
    exit 1
fi

# Dependencies
for cmd in git rsync curl; do
    command -v "$cmd" >/dev/null || { echo "❌ Missing dependency: $cmd"; exit 1; }
done
echo "✓ Dependencies satisfied"

# --- Migrate from legacy v0.2.x layout, if present -------------------
if [[ -e "$LEGACY_PLIST_FILE" ]] || [[ -d "$LEGACY_CACHE_DIR" ]] || [[ -d "$LEGACY_SUPPORT_DIR" ]]; then
    echo "Migrating from legacy claude-code-docs install…"
    launchctl bootout "gui/$UID/$LEGACY_PLIST_LABEL" 2>/dev/null || true
    rm -f "$LEGACY_PLIST_FILE"
    rm -rf "$LEGACY_CACHE_DIR"
    rm -rf "$LEGACY_SUPPORT_DIR"
    echo "✓ Legacy install cleared"
fi

# Wipe legacy git clone in docs dir (pre-v0.2)
if [[ -d "$CLAUDE_DOCS_DIR/.git" ]]; then
    echo "Removing legacy git clone at $CLAUDE_DOCS_DIR (will be replaced by flat mirror)…"
    rm -rf "$CLAUDE_DOCS_DIR"
fi

# Drop legacy /docs command (skills replace it)
[[ -f "$HOME/.claude/commands/docs.md" ]] && rm -f "$HOME/.claude/commands/docs.md" && echo "✓ Removed legacy /docs command"

# --- Cache clone -------------------------------------------------------
mkdir -p "$(dirname "$CACHE_DIR")"
if [[ -d "$CACHE_DIR/.git" ]]; then
    echo "Updating cache clone…"
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    echo "Cloning $REPO_URL → $CACHE_DIR"
    git clone --quiet --branch "$BRANCH" --single-branch "$REPO_URL" "$CACHE_DIR"
fi

# --- Write sync script -------------------------------------------------
mkdir -p "$SUPPORT_DIR"
cat > "$SYNC_SCRIPT" <<'SYNC_EOF'
#!/bin/bash
# Sync Agent Harness docs (Claude Code + Codex + OpenCode) into the user's
# home folders. Generated by install.sh — re-run installer to regenerate.
set -euo pipefail

CACHE_DIR="$HOME/Library/Caches/agent-harness-docs-mirror"
CLAUDE_DOCS_DIR="$HOME/claude-code-docs"
CODEX_DOCS_DIR="$HOME/codex-docs"
OPENCODE_DOCS_DIR="$HOME/opencode-docs"
BRANCH="main"
REPO_URL="https://github.com/mrkhachaturov/agent-harness-docs.git"

mkdir -p "$CLAUDE_DOCS_DIR" "$CODEX_DOCS_DIR" "$OPENCODE_DOCS_DIR"

# Refresh cache clone
if [[ -d "$CACHE_DIR/.git" ]]; then
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    git clone --quiet --branch "$BRANCH" --single-branch "$REPO_URL" "$CACHE_DIR"
fi

# Mirror each docset into its own flat folder
rsync -a --delete "$CACHE_DIR/docs/claude-code/" "$CLAUDE_DOCS_DIR/"
rsync -a --delete "$CACHE_DIR/docs/codex/"       "$CODEX_DOCS_DIR/"
rsync -a --delete "$CACHE_DIR/docs/opencode/"    "$OPENCODE_DOCS_DIR/"
SYNC_EOF
chmod +x "$SYNC_SCRIPT"
echo "✓ Sync script: $SYNC_SCRIPT"

# --- Initial sync ------------------------------------------------------
"$SYNC_SCRIPT"
CLAUDE_COUNT=$(find "$CLAUDE_DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
CODEX_COUNT=$(find "$CODEX_DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
OPENCODE_COUNT=$(find "$OPENCODE_DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
echo "✓ Synced $CLAUDE_COUNT Claude Code docs → $CLAUDE_DOCS_DIR"
echo "✓ Synced $CODEX_COUNT Codex docs        → $CODEX_DOCS_DIR"
echo "✓ Synced $OPENCODE_COUNT OpenCode docs   → $OPENCODE_DOCS_DIR"

# --- launchd plist (hourly) -------------------------------------------
mkdir -p "$LAUNCH_AGENTS_DIR"

# Unload existing plist if loaded (idempotent re-install)
launchctl bootout "gui/$UID/$PLIST_LABEL" 2>/dev/null || true

cat > "$PLIST_FILE" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$SYNC_SCRIPT</string>
    </array>
    <key>StartInterval</key>
    <integer>3600</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$SUPPORT_DIR/sync.log</string>
    <key>StandardErrorPath</key>
    <string>$SUPPORT_DIR/sync.err.log</string>
</dict>
</plist>
PLIST_EOF

launchctl bootstrap "gui/$UID" "$PLIST_FILE"
echo "✓ launchd job loaded: $PLIST_LABEL (runs hourly, also at login)"

# --- Detect installed indexer ----------------------------------------
# Each indexer variant has its own pre-rendered SKILL.md in the repo at
# skills/<docset>/<indexer>/SKILL.md. The installer picks the right one
# based on what's installed on this machine. "plain" is the fallback
# variant — assumes no semantic-search tool and tells the agent to use
# ls/grep/Read over the docs folder.
detect_indexer() {
    if command -v miyo >/dev/null 2>&1; then
        echo "miyo"
        return
    fi
    # Future indexers: probe their CLIs here, return the matching variant name.
    echo "plain"
}

INDEXER=$(detect_indexer)
echo "✓ Detected indexer: $INDEXER"

# --- Install Claude Code skill + rule ---------------------------------
mkdir -p "$CLAUDE_SKILL_DIR" "$(dirname "$CLAUDE_RULE_FILE")"
cp "$CACHE_DIR/skills/claude-code-docs/$INDEXER/SKILL.md" "$CLAUDE_SKILL_DIR/SKILL.md"
cp "$CACHE_DIR/rules/claude-code-docs.md" "$CLAUDE_RULE_FILE"
echo "✓ Installed Claude Code skill ($INDEXER): $CLAUDE_SKILL_DIR/SKILL.md"
echo "✓ Installed Claude Code rule:             $CLAUDE_RULE_FILE"

# --- Install Codex skill ----------------------------------------------
mkdir -p "$CODEX_SKILL_DIR"
cp "$CACHE_DIR/skills/codex-docs/$INDEXER/SKILL.md" "$CODEX_SKILL_DIR/SKILL.md"
echo "✓ Installed Codex skill ($INDEXER):        $CODEX_SKILL_DIR/SKILL.md"

# --- Install OpenCode-docs skill (shared across all three harnesses) --
# Canonical lives in ~/.agents/skills/ — both opencode and codex read it
# natively. For Claude Code, we add a symlink at ~/.claude/skills/.
mkdir -p "$OPENCODE_SKILL_DIR" "$(dirname "$OPENCODE_SKILL_CLAUDE_LINK")"
cp "$CACHE_DIR/skills/opencode-docs/$INDEXER/SKILL.md" "$OPENCODE_SKILL_DIR/SKILL.md"
echo "✓ Installed OpenCode-docs skill ($INDEXER): $OPENCODE_SKILL_DIR/SKILL.md"

# Replace whatever's at the Claude link path with a fresh symlink (handles
# upgrades from older versions that may have copied the file there).
if [[ -L "$OPENCODE_SKILL_CLAUDE_LINK" ]] || [[ -e "$OPENCODE_SKILL_CLAUDE_LINK" ]]; then
    rm -rf "$OPENCODE_SKILL_CLAUDE_LINK"
fi
ln -s "$OPENCODE_SKILL_DIR" "$OPENCODE_SKILL_CLAUDE_LINK"
echo "✓ Symlinked into Claude Code:              $OPENCODE_SKILL_CLAUDE_LINK → $OPENCODE_SKILL_DIR"

# --- Register Miyo MCP with both agent CLIs (only when miyo is the indexer)
register_miyo_mcp() {
    local agent="$1"  # "claude" or "codex"
    if ! command -v "$agent" >/dev/null 2>&1; then
        echo "  ($agent CLI not found — skip Miyo MCP registration)"
        return 0
    fi
    if "$agent" mcp list 2>/dev/null | grep -q -E '(^|[[:space:]])miyo([[:space:]]|:)'; then
        echo "  ($agent already has Miyo MCP registered — skip)"
        return 0
    fi
    if "$agent" mcp add miyo miyo mcp >/dev/null 2>&1; then
        echo "✓ Registered Miyo MCP with $agent CLI"
    else
        echo "  ⚠  Could not auto-register Miyo MCP with $agent — add manually: $agent mcp add miyo miyo mcp"
    fi
}

# --- Register Miyo MCP with opencode (JSON-merge into opencode.json[c]) --
# opencode has no `opencode mcp add` CLI — MCP servers live in opencode's
# global config under the `mcp` key. We merge into the file using python3
# (universal on macOS). If the file contains comments, we don't rewrite it;
# instead we print the snippet for manual paste, so user-authored comments
# stay intact.
register_miyo_mcp_opencode() {
    if ! command -v opencode >/dev/null 2>&1; then
        echo "  (opencode CLI not found — skip MCP registration in opencode)"
        return 0
    fi

    mkdir -p "$OPENCODE_CONFIG_DIR"

    local cfg=""
    if [[ -f "$OPENCODE_CONFIG_DIR/opencode.jsonc" ]]; then
        cfg="$OPENCODE_CONFIG_DIR/opencode.jsonc"
    elif [[ -f "$OPENCODE_CONFIG_DIR/opencode.json" ]]; then
        cfg="$OPENCODE_CONFIG_DIR/opencode.json"
    else
        # Create a fresh JSON config (.json, plain — no comments to worry about)
        cfg="$OPENCODE_CONFIG_DIR/opencode.json"
        cat > "$cfg" <<'NEWCFG'
{
  "$schema": "https://opencode.ai/config.json"
}
NEWCFG
        echo "  Created fresh $cfg"
    fi

    # python3 helper: load, ensure mcp.miyo exists, write back.
    # Handles .jsonc with comments only if comments are absent (otherwise
    # bails out so we don't lose them).
    OPENCODE_CFG="$cfg" python3 - <<'PY'
import json, os, re, sys
from pathlib import Path

cfg_path = Path(os.environ["OPENCODE_CFG"])
text = cfg_path.read_text()

has_line_comments  = re.search(r"(?m)^\s*//", text) is not None
has_block_comments = re.search(r"/\*.*?\*/", text, flags=re.DOTALL) is not None
if has_line_comments or has_block_comments:
    # Don't risk dropping user comments — print snippet and bail with code 2.
    print("HAS_COMMENTS")
    sys.exit(2)

# Plain JSON path: parse, merge, write back.
data = json.loads(text) if text.strip() else {}

mcp = data.setdefault("mcp", {})
if isinstance(mcp.get("miyo"), dict):
    miyo = mcp["miyo"]
    # Existing entry — only touch keys we own; don't disable if user disabled.
    miyo.setdefault("type", "local")
    miyo.setdefault("command", ["miyo", "mcp"])
    miyo.setdefault("enabled", True)
    if miyo.get("type") == "local" and miyo.get("command") != ["miyo", "mcp"]:
        # Respect a custom command the user set deliberately.
        pass
    print("UPDATED")
else:
    mcp["miyo"] = {
        "type": "local",
        "command": ["miyo", "mcp"],
        "enabled": True,
    }
    print("ADDED")

cfg_path.write_text(json.dumps(data, indent=2) + "\n")
PY
    local rc=$?
    case $rc in
        0)
            echo "✓ Merged Miyo MCP into $cfg"
            ;;
        2)
            echo "  ⚠  $cfg has comments — not editing automatically to preserve them."
            echo "     Add this manually to your $cfg under \"mcp\":"
            echo '       "miyo": { "type": "local", "command": ["miyo", "mcp"], "enabled": true }'
            ;;
        *)
            echo "  ⚠  Failed to merge Miyo MCP into $cfg (python3 returned $rc)"
            ;;
    esac
}

if [[ "$INDEXER" == "miyo" ]]; then
    echo "Wiring Miyo MCP into agent CLIs…"
    register_miyo_mcp claude
    register_miyo_mcp codex
    register_miyo_mcp_opencode
fi

# --- Done --------------------------------------------------------------
echo ""
echo "✅ Installed."
echo ""
echo "Indexer variant:    $INDEXER"
echo "Claude Code docs:   $CLAUDE_DOCS_DIR  ($CLAUDE_COUNT files)"
echo "Codex docs:         $CODEX_DOCS_DIR  ($CODEX_COUNT files)"
echo "OpenCode docs:      $OPENCODE_DOCS_DIR  ($OPENCODE_COUNT files)"
echo "Sync log:           $SUPPORT_DIR/sync.log"
echo "Skills:             /claude-code-docs (Claude Code)"
echo "                    /codex-docs (Codex)"
echo "                    /opencode-docs (Claude + Codex + OpenCode — shared)"
echo ""
if [[ "$INDEXER" == "miyo" ]]; then
    echo "Next: point Miyo at all three folders:"
    echo "  • $CLAUDE_DOCS_DIR    (label: claude-code-docs)"
    echo "  • $CODEX_DOCS_DIR     (label: codex-docs)"
    echo "  • $OPENCODE_DOCS_DIR  (label: opencode-docs)"
    echo ""
    echo "Then restart Claude Code, Codex, and OpenCode (if running) so the skills/rules/MCP load."
else
    echo "No semantic-search indexer detected — the plain skill variant was installed."
    echo "The agents will use ls/grep/Read against the docs folders directly."
    echo ""
    echo "If you'd like ranked semantic search, install one of:"
    echo "  • Miyo (https://miyo.md) — then re-run this installer to switch to the Miyo skill."
    echo ""
    echo "Restart Claude Code, Codex, and OpenCode (if running) so the skills/rules load."
fi
