#!/bin/bash
set -euo pipefail

# Agent Harness Docs Installer v0.3.0 — Miyo-aware dual-doc mirror
# (Claude Code + OpenAI Codex) with hourly launchd sync.
#
# What this installs:
#   ~/claude-code-docs/                                       Claude Code docs (flat)
#   ~/codex-docs/                                             Codex docs (flat)
#   ~/Library/Caches/agent-harness-docs-mirror/                cache git clone (full repo)
#   ~/Library/Application Support/agent-harness-docs/sync.sh   sync script (both targets)
#   ~/Library/LaunchAgents/com.mrkhachaturov.agent-harness-docs.plist   hourly job
#   ~/.claude/skills/claude-code-docs/SKILL.md                 Claude Code skill
#   ~/.claude/rules/claude-code-docs.md                        always-on rule
#   ~/.agents/skills/codex-docs/SKILL.md                       Codex skill (agentskills.io USER scope)
#
# It also registers the Miyo MCP server with both `claude` and `codex` CLIs
# if those CLIs are installed and Miyo isn't yet registered there.

REPO_URL="https://github.com/mrkhachaturov/agent-harness-docs.git"
BRANCH="main"

CLAUDE_DOCS_DIR="$HOME/claude-code-docs"
CODEX_DOCS_DIR="$HOME/codex-docs"

CACHE_DIR="$HOME/Library/Caches/agent-harness-docs-mirror"
SUPPORT_DIR="$HOME/Library/Application Support/agent-harness-docs"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_LABEL="com.mrkhachaturov.agent-harness-docs"
PLIST_FILE="$LAUNCH_AGENTS_DIR/$PLIST_LABEL.plist"
SYNC_SCRIPT="$SUPPORT_DIR/sync.sh"

CLAUDE_SKILL_DIR="$HOME/.claude/skills/claude-code-docs"
CLAUDE_RULE_FILE="$HOME/.claude/rules/claude-code-docs.md"
CODEX_SKILL_DIR="$HOME/.agents/skills/codex-docs"

# Legacy paths from v0.2.x (claude-code-docs era)
LEGACY_CACHE_DIR="$HOME/Library/Caches/claude-code-docs-mirror"
LEGACY_SUPPORT_DIR="$HOME/Library/Application Support/claude-code-docs"
LEGACY_PLIST_LABEL="com.mrkhachaturovclaude-code-docs"
LEGACY_PLIST_FILE="$LAUNCH_AGENTS_DIR/$LEGACY_PLIST_LABEL.plist"

echo "Agent Harness Docs Installer v0.3.0"
echo "==================================="

# Platform check — launchd is macOS-only
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ This installer targets macOS (uses launchd). Detected: $OSTYPE"
    exit 1
fi

# Dependencies
for cmd in git rsync curl; do
    command -v "$cmd" >/dev/null || { echo "❌ Missing dependency: $cmd"; exit 1; }
done
echo "✓ Dependencies satisfied"

# --- Migrate from legacy v0.2.x layout, if present -------------------
if [[ -e "$LEGACY_PLIST_FILE" ]] || [[ -d "$LEGACY_CACHE_DIR" ]] || [[ -d "$LEGACY_SUPPORT_DIR" ]]; then
    echo "Migrating from legacy claude-code-docs install…"
    launchctl bootout "gui/$UID/$LEGACY_PLIST_LABEL" 2>/dev/null || true
    rm -f "$LEGACY_PLIST_FILE"
    rm -rf "$LEGACY_CACHE_DIR"
    rm -rf "$LEGACY_SUPPORT_DIR"
    echo "✓ Legacy install cleared"
fi

# Wipe legacy git clone in docs dir (pre-v0.2)
if [[ -d "$CLAUDE_DOCS_DIR/.git" ]]; then
    echo "Removing legacy git clone at $CLAUDE_DOCS_DIR (will be replaced by flat mirror)…"
    rm -rf "$CLAUDE_DOCS_DIR"
fi

# Drop legacy /docs command (skills replace it)
[[ -f "$HOME/.claude/commands/docs.md" ]] && rm -f "$HOME/.claude/commands/docs.md" && echo "✓ Removed legacy /docs command"

# --- Cache clone -------------------------------------------------------
mkdir -p "$(dirname "$CACHE_DIR")"
if [[ -d "$CACHE_DIR/.git" ]]; then
    echo "Updating cache clone…"
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    echo "Cloning $REPO_URL → $CACHE_DIR"
    git clone --quiet --branch "$BRANCH" --single-branch "$REPO_URL" "$CACHE_DIR"
fi

# --- Write sync script -------------------------------------------------
mkdir -p "$SUPPORT_DIR"
cat > "$SYNC_SCRIPT" <<'SYNC_EOF'
#!/bin/bash
# Sync Agent Harness docs (Claude Code + Codex) into the user's home folders.
# Generated by install.sh — re-run installer to regenerate.
set -euo pipefail

CACHE_DIR="$HOME/Library/Caches/agent-harness-docs-mirror"
CLAUDE_DOCS_DIR="$HOME/claude-code-docs"
CODEX_DOCS_DIR="$HOME/codex-docs"
BRANCH="main"
REPO_URL="https://github.com/mrkhachaturov/agent-harness-docs.git"

mkdir -p "$CLAUDE_DOCS_DIR" "$CODEX_DOCS_DIR"

# Refresh cache clone
if [[ -d "$CACHE_DIR/.git" ]]; then
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    git clone --quiet --branch "$BRANCH" --single-branch "$REPO_URL" "$CACHE_DIR"
fi

# Mirror each docset into its own flat folder
rsync -a --delete "$CACHE_DIR/docs/claude-code/" "$CLAUDE_DOCS_DIR/"
rsync -a --delete "$CACHE_DIR/docs/codex/"       "$CODEX_DOCS_DIR/"
SYNC_EOF
chmod +x "$SYNC_SCRIPT"
echo "✓ Sync script: $SYNC_SCRIPT"

# --- Initial sync ------------------------------------------------------
"$SYNC_SCRIPT"
CLAUDE_COUNT=$(find "$CLAUDE_DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
CODEX_COUNT=$(find "$CODEX_DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
echo "✓ Synced $CLAUDE_COUNT Claude Code docs → $CLAUDE_DOCS_DIR"
echo "✓ Synced $CODEX_COUNT Codex docs        → $CODEX_DOCS_DIR"

# --- launchd plist (hourly) -------------------------------------------
mkdir -p "$LAUNCH_AGENTS_DIR"

# Unload existing plist if loaded (idempotent re-install)
launchctl bootout "gui/$UID/$PLIST_LABEL" 2>/dev/null || true

cat > "$PLIST_FILE" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$SYNC_SCRIPT</string>
    </array>
    <key>StartInterval</key>
    <integer>3600</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$SUPPORT_DIR/sync.log</string>
    <key>StandardErrorPath</key>
    <string>$SUPPORT_DIR/sync.err.log</string>
</dict>
</plist>
PLIST_EOF

launchctl bootstrap "gui/$UID" "$PLIST_FILE"
echo "✓ launchd job loaded: $PLIST_LABEL (runs hourly, also at login)"

# --- Detect installed indexer ----------------------------------------
# Each indexer variant has its own pre-rendered SKILL.md in the repo at
# skills/<docset>/<indexer>/SKILL.md. The installer picks the right one
# based on what's installed on this machine. "plain" is the fallback
# variant — assumes no semantic-search tool and tells the agent to use
# ls/grep/Read over the docs folder.
detect_indexer() {
    if command -v miyo >/dev/null 2>&1; then
        echo "miyo"
        return
    fi
    # Future indexers: probe their CLIs here, return the matching variant name.
    echo "plain"
}

INDEXER=$(detect_indexer)
echo "✓ Detected indexer: $INDEXER"

# --- Install Claude Code skill + rule ---------------------------------
mkdir -p "$CLAUDE_SKILL_DIR" "$(dirname "$CLAUDE_RULE_FILE")"
cp "$CACHE_DIR/skills/claude-code-docs/$INDEXER/SKILL.md" "$CLAUDE_SKILL_DIR/SKILL.md"
cp "$CACHE_DIR/rules/claude-code-docs.md" "$CLAUDE_RULE_FILE"
echo "✓ Installed Claude Code skill ($INDEXER): $CLAUDE_SKILL_DIR/SKILL.md"
echo "✓ Installed Claude Code rule:             $CLAUDE_RULE_FILE"

# --- Install Codex skill ----------------------------------------------
mkdir -p "$CODEX_SKILL_DIR"
cp "$CACHE_DIR/skills/codex-docs/$INDEXER/SKILL.md" "$CODEX_SKILL_DIR/SKILL.md"
echo "✓ Installed Codex skill ($INDEXER):        $CODEX_SKILL_DIR/SKILL.md"

# --- Register Miyo MCP with both agent CLIs (only when miyo is the indexer)
register_miyo_mcp() {
    local agent="$1"  # "claude" or "codex"
    if ! command -v "$agent" >/dev/null 2>&1; then
        echo "  ($agent CLI not found — skip Miyo MCP registration)"
        return 0
    fi
    if "$agent" mcp list 2>/dev/null | grep -q -E '(^|[[:space:]])miyo([[:space:]]|:)'; then
        echo "  ($agent already has Miyo MCP registered — skip)"
        return 0
    fi
    if "$agent" mcp add miyo miyo mcp >/dev/null 2>&1; then
        echo "✓ Registered Miyo MCP with $agent CLI"
    else
        echo "  ⚠  Could not auto-register Miyo MCP with $agent — add manually: $agent mcp add miyo miyo mcp"
    fi
}

if [[ "$INDEXER" == "miyo" ]]; then
    echo "Wiring Miyo MCP into agent CLIs…"
    register_miyo_mcp claude
    register_miyo_mcp codex
fi

# --- Done --------------------------------------------------------------
echo ""
echo "✅ Installed."
echo ""
echo "Indexer variant:    $INDEXER"
echo "Claude Code docs:   $CLAUDE_DOCS_DIR  ($CLAUDE_COUNT files)"
echo "Codex docs:         $CODEX_DOCS_DIR  ($CODEX_COUNT files)"
echo "Sync log:           $SUPPORT_DIR/sync.log"
echo "Skills:             /claude-code-docs (Claude Code)"
echo "                    /codex-docs (Codex — auto-discovered via SKILL metadata)"
echo ""
if [[ "$INDEXER" == "miyo" ]]; then
    echo "Next: point Miyo at BOTH folders:"
    echo "  • $CLAUDE_DOCS_DIR  (label: claude-code-docs)"
    echo "  • $CODEX_DOCS_DIR   (label: codex-docs)"
    echo ""
    echo "Then restart Claude Code (and Codex if running) so the skills/rules load."
else
    echo "No semantic-search indexer detected — the plain skill variant was installed."
    echo "The agents will use ls/grep/Read against the docs folders directly."
    echo ""
    echo "If you'd like ranked semantic search, install one of:"
    echo "  • Miyo (https://miyo.md) — then re-run this installer to switch to the Miyo skill."
    echo ""
    echo "Restart Claude Code (and Codex if running) so the skills/rules load."
fi
