#!/bin/bash
set -euo pipefail

# Claude Code Docs Installer v0.2.0 — Miyo-aware flat mirror with hourly sync
#
# What this installs:
#   ~/claude-code-docs/                                       flat folder, only .md docs at root
#   ~/Library/Caches/claude-code-docs-mirror/                  cache git clone (full repo)
#   ~/Library/Application Support/claude-code-docs/sync.sh     sync script
#   ~/Library/LaunchAgents/com.mrkhachaturovclaude-code-docs.plist   hourly job
#   ~/.claude/skills/claude-code-docs/SKILL.md                 Miyo-based skill
#   ~/.claude/rules/claude-code-docs.md                        always-on hint to use the skill

REPO_URL="https://github.com/mrkhachaturov/claude-code-docs.git"
BRANCH="main"

DOCS_DIR="$HOME/claude-code-docs"
CACHE_DIR="$HOME/Library/Caches/claude-code-docs-mirror"
SUPPORT_DIR="$HOME/Library/Application Support/claude-code-docs"
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_LABEL="com.mrkhachaturovclaude-code-docs"
PLIST_FILE="$LAUNCH_AGENTS_DIR/$PLIST_LABEL.plist"
SYNC_SCRIPT="$SUPPORT_DIR/sync.sh"
SKILL_DIR="$HOME/.claude/skills/claude-code-docs"
RULE_FILE="$HOME/.claude/rules/claude-code-docs.md"

echo "Claude Code Docs Installer v0.2.0"
echo "================================="

# Platform check — launchd is macOS-only
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ This installer targets macOS (uses launchd). Detected: $OSTYPE"
    exit 1
fi

# Dependencies
for cmd in git rsync curl; do
    command -v "$cmd" >/dev/null || { echo "❌ Missing dependency: $cmd"; exit 1; }
done
echo "✓ Dependencies satisfied"

# --- Wipe legacy install if present ------------------------------------
if [[ -d "$DOCS_DIR/.git" ]]; then
    echo "Removing legacy git clone at $DOCS_DIR (will be replaced by flat mirror)…"
    rm -rf "$DOCS_DIR"
fi

# Drop legacy /docs command (skill replaces it)
[[ -f "$HOME/.claude/commands/docs.md" ]] && rm -f "$HOME/.claude/commands/docs.md" && echo "✓ Removed legacy /docs command"

# --- Cache clone -------------------------------------------------------
mkdir -p "$(dirname "$CACHE_DIR")"
if [[ -d "$CACHE_DIR/.git" ]]; then
    echo "Updating cache clone…"
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    echo "Cloning $REPO_URL → $CACHE_DIR"
    git clone --quiet --branch "$BRANCH" --single-branch "$REPO_URL" "$CACHE_DIR"
fi

# --- Write sync script -------------------------------------------------
mkdir -p "$SUPPORT_DIR"
cat > "$SYNC_SCRIPT" <<'SYNC_EOF'
#!/bin/bash
# Sync Claude Code docs from upstream into ~/claude-code-docs/
# Generated by install.sh — re-run installer to regenerate.
set -euo pipefail

CACHE_DIR="$HOME/Library/Caches/claude-code-docs-mirror"
DOCS_DIR="$HOME/claude-code-docs"
BRANCH="main"

mkdir -p "$DOCS_DIR"

# Refresh cache clone
if [[ -d "$CACHE_DIR/.git" ]]; then
    git -C "$CACHE_DIR" fetch --quiet origin "$BRANCH"
    git -C "$CACHE_DIR" reset --hard --quiet "origin/$BRANCH"
else
    git clone --quiet --branch "$BRANCH" --single-branch \
        "https://github.com/mrkhachaturov/claude-code-docs.git" "$CACHE_DIR"
fi

# Mirror docs/ contents into the flat folder
rsync -a --delete "$CACHE_DIR/docs/" "$DOCS_DIR/"
SYNC_EOF
chmod +x "$SYNC_SCRIPT"
echo "✓ Sync script: $SYNC_SCRIPT"

# --- Initial sync ------------------------------------------------------
"$SYNC_SCRIPT"
DOC_COUNT=$(find "$DOCS_DIR" -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')
echo "✓ Synced $DOC_COUNT docs into $DOCS_DIR"

# --- launchd plist (hourly) -------------------------------------------
mkdir -p "$LAUNCH_AGENTS_DIR"

# Unload existing plist if loaded (idempotent re-install)
launchctl bootout "gui/$UID/$PLIST_LABEL" 2>/dev/null || true

cat > "$PLIST_FILE" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$SYNC_SCRIPT</string>
    </array>
    <key>StartInterval</key>
    <integer>3600</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$SUPPORT_DIR/sync.log</string>
    <key>StandardErrorPath</key>
    <string>$SUPPORT_DIR/sync.err.log</string>
</dict>
</plist>
PLIST_EOF

launchctl bootstrap "gui/$UID" "$PLIST_FILE"
echo "✓ launchd job loaded: $PLIST_LABEL (runs hourly, also at login)"

# --- Install skill + rule ---------------------------------------------
mkdir -p "$SKILL_DIR" "$(dirname "$RULE_FILE")"
cp "$CACHE_DIR/skills/claude-code-docs/SKILL.md" "$SKILL_DIR/SKILL.md"
cp "$CACHE_DIR/rules/claude-code-docs.md" "$RULE_FILE"
echo "✓ Installed skill: $SKILL_DIR/SKILL.md"
echo "✓ Installed rule:  $RULE_FILE"

# --- Done --------------------------------------------------------------
echo ""
echo "✅ Installed."
echo ""
echo "Folder:       $DOCS_DIR  ($DOC_COUNT docs, flat)"
echo "Sync log:     $SUPPORT_DIR/sync.log"
echo "Skill:        /claude-code-docs"
echo ""
echo "Next: point Miyo at $DOCS_DIR (label it 'claude-code-docs')"
echo "      Restart Claude Code so the new skill/rule load."
